---
include: https://raw.githubusercontent.com/hassio-addons/organization/master/gitlabci/addon.yml

variables:
  ADDON_GITHUB_REPO: "hassio-addons/addon-matrix"
  ADDON_SLUG: "matrix"
  ADDON_TARGET: "matrix"

  ADDON_LEGACY_TAGS: "true"

  ADDON_AARCH64_BASE: "hassioaddons/base-python-aarch64:3.0.2"
  ADDON_AMD64_BASE: "hassioaddons/base-python-amd64:3.0.2"
  ADDON_ARMHF_BASE: "hassioaddons/base-python-armhf:3.0.2"
  ADDON_ARMV7_BASE: "hassioaddons/base-python-armv7:3.0.2"
  ADDON_I386_BASE: "hassioaddons/base-python-i386:3.0.2"
